FROM centos:7.6.1810

COPY vexdb-5.0.0-CentOS-64bit.tar.bz2 .
COPY gosu-amd64 /usr/local/bin/gosu

ENV LANG en_US.utf8

#RUN yum install -y epel-release

RUN set -eux; \
    yum install -y bzip2 bzip2-devel curl libaio&& \
    groupadd -g 70 omm;  \
    useradd -u 70 -g omm -d /home/omm omm;  \
    mkdir -p /var/lib/vexdb && \
    mkdir -p /usr/local/vexdb && \
    mkdir -p /var/run/vexdb  && \
    mkdir /docker-entrypoint-initdb.d && \
    tar -jxf vexdb-5.0.0-CentOS-64bit.tar.bz2 -C /usr/local/vexdb && \
    chown -R omm:omm /var/run/vexdb && chown -R omm:omm /usr/local/vexdb && chown -R omm:omm /var/lib/vexdb &&  chown -R omm:omm /docker-entrypoint-initdb.d && \
    chmod 2777 /var/run/vexdb && \
    rm -rf vexdb-5.0.0-CentOS-64bit.tar.bz2 && yum clean all

RUN set -eux; \
    echo "export GAUSSHOME=/usr/local/vexdb"  >> /home/omm/.bashrc && \
    echo "export PATH=\$GAUSSHOME/bin:\$PATH " >> /home/omm/.bashrc && \
    echo "export LD_LIBRARY_PATH=\$GAUSSHOME/lib:\$LD_LIBRARY_PATH" >> /home/omm/.bashrc

ENV GOSU_VERSION 1.12
RUN set -eux; \
     chmod +x /usr/local/bin/gosu


ENV PGDATA /var/lib/vexdb/data

COPY entrypoint.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/entrypoint.sh;ln -s /usr/local/bin/entrypoint.sh / # backwards compat

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 5432
CMD ["vexdb"]
